name: Publish Release

on:
  release:
    types:
      - published

jobs:
  base-publish:
    if: startsWith(github.event.head_commit.message, 'bump:')
    name: ESLint Config Base Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./base
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  typescript-publish:
    if: startsWith(github.event.head_commit.message, 'bump:')
    name: ESLint Config Typescript Publish
    runs-on: ubuntu-latest
    needs: base-publish
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Bump base config
        run: |
          npm install @teknologi-umum/eslint-config-base@latest
          npm version patch
      - name: Commit lockfile
        run: |
          git config --global user.name 'elianiva'
          git config --global user.email 'elianiva@users.noreply.github.com'
          git commit -am 'chore: bump config-typescript lockfile'
          git push
      - run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
